version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: alimed_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: alimed_db
      MYSQL_USER: alimed_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - alimed_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../WebAPI/API.Alimed
      dockerfile: Dockerfile
    container_name: alimed_backend
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5056
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=alimed_db;User=alimed_user;Password=${MYSQL_PASSWORD};
      - Jwt__Key=${JWT_SECRET_KEY}
      - Jwt__Issuer=https://alimed.app
      - Jwt__Audience=https://alimed.app
      - GitHub__ClientId=${GITHUB_CLIENT_ID}
      - GitHub__ClientSecret=${GITHUB_CLIENT_SECRET}
    ports:
      - "5056:5056"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - alimed_network

volumes:
  mysql_data:


networks:
  alimed_network:
    driver: bridge
